# node_exporter
node_exporter_version: '1.8.0'

# promtail
promtail_version: '2.9.8'

# go
go_version: '1.22.3'

# cosmovisor
cosmovisor_version: 'v1.5.0'
cosmovisor_service_name: 'cosmovisor-{{ network }}'

# config
node_exporter: true
promtail: false
nginx: false
enableapi: false
enablegrpc: false
publicrpc: false

# horcrux
horcrux_repo: 'https://github.com/strangelove-ventures/horcrux.git'
horcrux_version: 'v3.3.0'
horcrux_cosigner_port: 2222