# node_exporter
node_exporter_version: '1.9.1'

# promtail
promtail_version: '2.9.8'

# go
go_version: '1.23.12'

# cosmovisor
cosmovisor_version: 'v1.7.1'
cosmovisor_service_name: 'cosmovisor-{{ service_prefix }}'

# config
service_prefix: "{{ chain }}"
node_exporter: true
promtail: false
nginx: false
enableapi: false
enablegrpc: false
publicrpc: false
indexer: "null"
app_parameters: null
config_parameters: null
custom_init_params: ""
custom_start_params: ""

# horcrux
horcrux_repo: 'https://github.com/strangelove-ventures/horcrux.git'
horcrux_version: 'v3.3.2'
horcrux_cosigner_port: 2222