folder: '.babylond'
daemon: babylond
chain_id: bbn-test-3
node_version: v0.8.3
repo: 'https://github.com/babylonchain/babylon.git'
genesis: 'https://snapshots.polkachu.com/testnet-genesis/babylon/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:20656'
addrbook_file: 'https://snapshots.polkachu.com/testnet-addrbook/babylon/addrbook.json'
snapshot_url: 'https://snapshots.polkachu.com/testnet-snapshots/babylon/babylon_32018.tar.lz4'
minimum_gas_price: '0.00001ubbn'
custom_port_prefix: 109