network: terra
folder: '.terra'
daemon: terrad
chain_id: pisco-1
node_version: 'v2.11.0'
repo: https://github.com/terra-money/core
genesis: 'https://snapshots.polkachu.com/testnet-genesis/terra/genesis.json'
addrbook_file: 'https://snapshots.polkachu.com/testnet-addrbook/terra/addrbook.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:11756'
snapshot_url: 'https://snapshots.polkachu.com/testnet-snapshots/terra/terra_11426486.tar.lz4'
custom_port_prefix: 116
#upgrade_folder: v1.9
minimum_gas_price: '0.015uluna'
enable_priv_validator_laddr: false